### ISSUE TITLE
[bug]: Recent test runs page does not show new test runs unless page is refreshed

### ISSUE THREAD

**Issue by madhavsikka** [keploy/ui#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

**Current behaviour:** The `http://localhost:8000/testruns` page does not get updated if go project tests are run again, unless the browser page is refreshed. The test runs are not shown even if user navigates around to some other page and then comes back to the test runs page.

**Expected behaviour:** Updated test runs should be shown.

### Steps to reproduce

1. Go to `http://localhost:8000/testruns`
2. Execute ` go test -coverpkg=./... -covermode=atomic  ./...` in go project
3. Test run is not shown on `http://localhost:8000/testruns`
4. Navigate around to some other page like `http://localhost:8000/testlist` and come back to `http://localhost:8000/testruns`
5. New test run is still not shown
6. Refresh the page, the new test run is visible then

### Environment

Production

### Version

Local

**Comment by madhavsikka** [comment]
I think updating useQuery's fetchPolicy to 'cache-and-network' fixes this

**Comment by nehagup** [comment]
Thanks for creating the issue @madhavsikka. Will fix this asap! :)

**Comment by madhavsikka** [comment]
On second thought, should the query be polled after some interval. So that user does not need to refresh ? @nehagup

**Comment by slayerjain** [comment]
@madhavsikka I think that's a great idea. I found some docs for that here - https://www.apollographql.com/docs/react/data/queries/#polling

Also, what do you think about using graphql subscription in the future? Do you think it would have benefits over polling for some of the queries? could be something we can discuss for the future 🤔

**Comment by madhavsikka** [comment]
Haven't explored subscriptions before, so can't say. 
Cool, I'll work on polling the query.
