### ISSUE TITLE
[feature]: Add Datagrid to list all the test runs (UI improvement)

### ISSUE THREAD

**Issue by namantaneja167** [keploy/ui#36]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Adding Datagrid instead of cards on the "/testruns" page makes it easier to sort out test runs according to users need 

### Why should this be worked on?

- Makes it easier to sort out required test run data based on their need. 
- A better UX experience for the user.

**Comment by nehagup** [comment]
This is a duplicate issue https://github.com/keploy/ui/issues/4
