### ISSUE TITLE
[bug]: The sidebar is having UI inconsistency in opened and close state

### ISSUE THREAD

**Issue by Janvi-Thakkar** [keploy/ui#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we click on hamburger to open the sidebar, elements move down and when we click on the arrow button to close the sidebar, elements move up.

### Steps to reproduce

1) Go to [Keploy UI landing page.](http://localhost:8000/testlist)
2) Click on hamburger, observe the behavior.
3) Click on the arrow to close the sidebar, observe the behavior.

### Version

Local

**Comment by Janvi-Thakkar** [comment]
@nehagup may I work on this?

**Comment by nehagup** [comment]
@Janvi-Thakkar Yes, Sure!! 👏
