### ISSUE TITLE
[bug]: URL field of HttpReq is deleted on editing the testcase properties

### ISSUE THREAD

**Issue by re-Tick** [keploy/ui#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i change some properties of a testcase, then the URL in HttpReq of testcase is deleted that results in testrun failure for the updated testcase. This is because the the url field is not present in graphql query object which is upserted to keploy database. 
 Following is the testrun after updating a testcase property:
<img width="1280" alt="Screenshot 2022-05-10 at 1 11 09 PM" src="https://user-images.githubusercontent.com/60597329/167575592-d0ad4946-6a6b-4467-9710-9fc4968ee760.png">

### Steps to reproduce

1. Update a testcase and save the changes.
2. Run your app on test mode.
3. Testrun for the updated testcase will fail with 404 status code.

### Version

Local

**Comment by re-Tick** [comment]
This is resolved [#45](https://github.com/keploy/keploy/pull/45)

**Comment by nehagup** [comment]
This has occurred due to  - https://github.com/keploy/keploy/blob/60acbdcbb289ccfab79eaa5829ac573e0173b610/graph/schema.graphqls#L27 

Thanks for raising this. I'm working on this.
