### ISSUE TITLE
[bug]: unable to save the changes in response

### ISSUE THREAD

**Issue by re-Tick** [keploy/ui#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try saving the changes of testcase, the operation fails throwing the following network message. 

<img width="1280" alt="Screenshot 2022-05-27 at 12 08 06 PM" src="https://user-images.githubusercontent.com/60597329/170645611-229baaeb-039d-4cce-9ca7-d8d7fd50def0.png">

### Steps to reproduce

1. Go to testcase tab on http://localhost:8081/testlist
2. Open a testcase and edit the response.
3. Now, click on save.
4. "Failed to update!" is displayed.

### Version

Local

**Comment by nehagup** [comment]
@re-Tick thanks for reporting, I tried re-creating this issue but couldn't succeed. Can you please post the request, response of this test case?

I suspect it might be a bug with a particular timestamp field which I'm not covering locally.

**Comment by re-Tick** [comment]
Here, It is screenshot of the testcase passed to the mutation.
<img width="1280" alt="Screenshot 2022-06-05 at 10 02 46 PM" src="https://user-images.githubusercontent.com/60597329/172060841-11b15a49-6289-415e-9d8f-20bff31e22d3.png">

<img width="1280" alt="Screenshot 2022-06-05 at 10 02 46 PM" src="https://user-images.githubusercontent.com/60597329/172060768-119943fe-31f7-49a2-92f5-3423499a0941.png">

**Comment by nehagup** [comment]
@re-Tick As discussed, this might be typescript SDK specific bug as it's working locally(tested with Golang apps). Feel free to re-open the issue in case it occurs.
