### ISSUE TITLE
[bug]: Unable to normalize a failed testrun.

### ISSUE THREAD

**Issue by re-Tick** [keploy/ui#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to normalize the response of a failed testrun. The operation fails.

<img width="1280" alt="Screenshot 2022-05-27 at 1 09 44 PM" src="https://user-images.githubusercontent.com/60597329/170653372-84aea143-f4ff-4309-afc0-fbb7d8214936.png">

### Steps to reproduce

1. Capture the testcase on local Keploy server.
2. Change your local server responses and run the testrun.
3. Normalize the failed testcases using keploy ui.
4. "Failed to Update!" is displayed. 

### Version

Local

**Comment by nehagup** [comment]
RCA - Seems like the feature of normalising multiple test cases on the backend broke the frontend graphql API since the schema changed here. https://github.com/keploy/keploy/commit/b1bee04356bc3b096996967b5bb93c853b1c068d

**Comment by nehagup** [comment]
https://github.com/keploy/keploy/pull/68
