### ISSUE TITLE
[feature]: Add a hamburger button for applications under test cases

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/ui#77]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

When we navigate to the test cases section at keploy server, the applications tested are listed on the left (here-superhero-api). We can add a hamburger button to hide and show them as per user's convenience like the one done for Test cases and Test runs.

![Screenshot from 2022-10-05 15-28-14](https://user-images.githubusercontent.com/74777863/194034622-b8f9e580-7360-4cb3-ac6a-1c21531bd6e2.png)

### Why should this be worked on?

This feature will make the UI more responsive

**Comment by titanventura** [comment]
Would like to work on this. Can you assign me to this issue ?

**Comment by titanventura** [comment]
Hey. Is there an update on this PR ?

**Comment by titanventura** [comment]
ping @SanskritiHarmukh

**Comment by nehagup** [comment]
@titanventura my apologies I couldn't look into this. I will review and merge the PR this week itself. Thanks for reminding.

**Comment by titanventura** [comment]
ping @nehagup
