### ISSUE TITLE
[feature]: Improve messaging in Keploy console

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/ui#78]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

In the below case, I am not sending any data to my API thus the request body is empty, to present this in a better way we can have a proper message like- `Body is empty`. 

![Screenshot from 2022-10-05 15-58-02](https://user-images.githubusercontent.com/74777863/194040356-5643ef6c-2139-41a9-a3b0-8810abec2517.png)

Like in the below image we can see there are no dependencies thus displaying `empty`.

![Screenshot from 2022-10-05 16-02-17](https://user-images.githubusercontent.com/74777863/194040623-23e93a84-ea86-40ad-91cd-4fee987bbf01.png)

### Why should this be worked on?

This will add details to the section that is simply blank. Helps in user interaction.

**Comment by ompiepy** [comment]
@SanskritiHarmukh I would like to contribute in this issue. May I request you to assign this to me. Thanks.

**Comment by ompiepy** [comment]
@SanskritiHarmukh @nehagup Hello, I am new to docker. May I request you to guide to right track?
I followed the Installation guide. I entered the followign code:
1. git clone https://github.com/keploy/keploy.git
2. cd keploy
3. docker-compose -f docker-compose-dev.yaml up --build

![image](https://user-images.githubusercontent.com/66164291/194763982-fd64bcb0-a328-4332-a2ba-001c41ed6cc1.png)
and got stuck here. What should I do now? Is this docker build process complete and where to enter the subsequent commands after the step 3. like cloning the ui files.etc.

**Comment by nehagup** [comment]
@ompiepy You have ran the keploy server, now you need to clone the UI repo outside this directory. You can follow the contribution instructions on the UI repository.

**Comment by valasubramanian-tw** [comment]
@SanskritiHarmukh @nehagup I can quickly fix this minor issue. Can you assign it to me?

**Comment by nehagup** [comment]
@valasubramanian-tw sure.

**Comment by valasubramanian-tw** [comment]
@nehagup Does below attachment satisfy your expectation? 

<img width="851" alt="Screenshot 2022-10-23 at 10 45 12 PM" src="https://user-images.githubusercontent.com/110656887/197405900-cd13dfe5-f72e-4a28-bf3a-f49acfbb48db.png">
