### ISSUE TITLE
[feature]: Change the icon for keploy console

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/ui#80]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

The keploy icon for the UI is currently [this](https://github.com/keploy/ui/blob/main/src/images/gatsby-icon.png) that need to be changed to a newer one. Also, as the current icon is not square we are getting warnings for the gatsby dependency. Take reference from [here](https://avatars.githubusercontent.com/u/92252339?s=200&v=4).

### Why should this be worked on?

As keploy logo changed, the update need to reflected in the necessary places.

**Comment by ompiepy** [comment]
Hello @SanskritiHarmukh @nehagup . I want to contribute to this project. Please, assign this task to me. I will start working and send the PR. Thanks

**Comment by SanskritiHarmukh** [comment]
Sure @ompiepy

**Comment by ompiepy** [comment]
Which is the latest logo for the keploy? Is this the logo the latest one https://github.com/keploy/ui/blob/main/src/images/gatsby-icon.png? @SanskritiHarmukh

**Comment by ompiepy** [comment]
@SanskritiHarmukh Is the keploy Console and the keploy UI the same thing?

**Comment by SanskritiHarmukh** [comment]
@ompiepy I have attached the new image in the issue. 
Linking it again- https://avatars.githubusercontent.com/u/92252339?s=200&v=4

And yes they are the same thing.

**Comment by ompiepy** [comment]
@nehagup @SanskritiHarmukh How can I configure this? `export GATSBY_API_URL=http://localhost:8081/api`

**Comment by nehagup** [comment]
@ompiepy you just need to paste this on your CLI where you are going to run the UI

**Comment by murugesanp** [comment]
@SanskritiHarmukh I have opened the PR for this issue. Please validate and also assign this issue to me.

**Comment by murugesanp** [comment]
@nehagup can you give hactoberfest accepted label.?
