### ISSUE TITLE
[bug]: Spelling Typo in https://github.com/keploy/ui#readme

### ISSUE THREAD

**Issue by ompiepy** [keploy/ui#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Under the [Installation section ](https://github.com/keploy/ui#installation) the spelling is currently `QuickStar/Installation guide` in the place of `QuickStart/Installation guide'

### Steps to reproduce

1. Go to https://github.com/keploy/ui#installation

### Environment

Release

### Version

Cloud

**Comment by ompiepy** [comment]
May I send the PR for this?

**Comment by ompiepy** [comment]
Could you please reveiew this PR.

**Comment by nehagup** [comment]
@ompiepy thanks for raising this issue. Can you please make a PR to this repo from the forked repo.
